# Generated by Django 5.1 on 2025-05-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('persona', '0005_alter_persona_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idTurno', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('nutricionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='persona.nutricionista')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Turno',
            },
        ),
    ]
