# Generated by Django 5.1 on 2024-12-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('idProceso', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_progreso/')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('FechaProg', models.DateField()),
                ('PesoActual', models.FloatField()),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='persona.nutricionista', unique=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Progreso',
            },
        ),
    ]
