# Generated by Django 5.1 on 2025-05-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('persona', '0005_alter_persona_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('idProceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('indice_grasa_corporal', models.FloatField(blank=True, null=True)),
                ('perimetro_cintura', models.FloatField(blank=True, null=True)),
                ('perimetro_cadera', models.FloatField(blank=True, null=True)),
                ('perimetro_muslo', models.FloatField(blank=True, null=True)),
                ('perimetro_brazo', models.FloatField(blank=True, null=True)),
                ('perimetro_pecho', models.FloatField(blank=True, null=True)),
                ('masa_muscular', models.FloatField(blank=True, null=True)),
                ('agua_corporal', models.FloatField(blank=True, null=True)),
                ('tension_arterial_maxima', models.FloatField(blank=True, null=True)),
                ('tension_arterial_minima', models.FloatField(blank=True, null=True)),
                ('nutricionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='persona.nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Progreso',
                'ordering': ['-fecha'],
                'unique_together': {('paciente', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='FotoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_progreso/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField()),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='progreso.progreso')),
            ],
            options={
                'db_table': 'FotoProgreso',
            },
        ),
    ]
