# Generated by Django 5.1 on 2025-04-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progreso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='nutricionista',
        ),
    ]
