# Generated by Django 5.1 on 2024-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('numDocumento', models.CharField(max_length=20, unique=True)),
                ('tipoDocumento', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Nutricionista',
            },
        ),
    ]
