# Generated by Django 5.1 on 2025-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
