# Generated by Django 5.1 on 2025-04-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_rename_sexo_persona_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(max_length=20),
        ),
    ]
