# Generated by Django 5.1 on 2025-01-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisLab',
            fields=[
                ('idAnalisis', models.AutoField(primary_key=True, serialize=False)),
                ('hepatograma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creatininaSerica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uricemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterolTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uremia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hdl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ldl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trigiceridos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaB12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('albumina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perritina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('globulosRojos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leucositos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hematocrito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaD', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'AnalisisLab',
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('idAnamnesis', models.AutoField(primary_key=True, serialize=False)),
                ('habitos', models.CharField(max_length=100)),
                ('preferencia', models.CharField(max_length=100)),
                ('frecConsumo', models.CharField(max_length=100)),
                ('registroComida', models.TextField()),
                ('alimActual', models.TextField()),
            ],
            options={
                'db_table': 'Anamnesis',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('idHistoriaClinica', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.TextField()),
                ('suplemento', models.TextField()),
                ('alergia', models.TextField()),
                ('edad', models.PositiveIntegerField()),
                ('fechaNac', models.DateField()),
                ('intolerancia', models.TextField()),
                ('anteFamiliar', models.TextField()),
                ('antePatologico', models.TextField()),
                ('patologiaActual', models.TextField()),
                ('hsActiFisica', models.IntegerField()),
                ('tipoActiFisica', models.TextField()),
                ('actiLaboral', models.TextField()),
                ('sexo', models.TextField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'historiaclinica',
            },
        ),
    ]
