# Generated by Django 5.1 on 2024-12-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('numDocumento', models.CharField(max_length=20, unique=True)),
                ('tipoDocumento', models.CharField(max_length=10)),
                ('obraSocial', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('idHistoriaClinica', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.TextField()),
                ('suplemento', models.TextField()),
                ('alergia', models.TextField()),
                ('edad', models.PositiveIntegerField()),
                ('fechaNac', models.DateField()),
                ('intolerancia', models.TextField()),
                ('anteFamiliar', models.TextField()),
                ('antePatologico', models.TextField()),
                ('patologiaActual', models.TextField()),
                ('hsActiFisica', models.IntegerField()),
                ('tipoActiFisica', models.TextField()),
                ('actiLaboral', models.TextField()),
                ('sexo', models.TextField()),
                ('comentario', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'historiaclinica',
                'unique_together': {('paciente', 'idHistoriaClinica')},
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('idAnamnesis', models.AutoField(primary_key=True, serialize=False)),
                ('habitos', models.CharField(max_length=100)),
                ('preferencia', models.CharField(max_length=100)),
                ('frecConsumo', models.CharField(max_length=100)),
                ('registroComida', models.TextField()),
                ('alimActual', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Anamnesis',
                'unique_together': {('paciente', 'idAnamnesis')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisLab',
            fields=[
                ('idAnalisis', models.AutoField(primary_key=True, serialize=False)),
                ('hepatograma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creatininaSerica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uricemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterolTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uremia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hdl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ldl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trigiceridos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaB12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('albumina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perritina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('globulosRojos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leucositos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hematocrito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaD', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_lab', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'AnalisisLab',
                'unique_together': {('paciente', 'idAnalisis')},
            },
        ),
        migrations.CreateModel(
            name='ValorAntropometrico',
            fields=[
                ('idValorAntropometrico', models.AutoField(primary_key=True, serialize=False)),
                ('masaMuscular', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masaGrasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circunferencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valores_antropometricos', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'ValorAntropometrico',
                'unique_together': {('paciente', 'idValorAntropometrico')},
            },
        ),
    ]
