# Generated by Django 5.1 on 2025-05-09 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0005_alter_persona_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('obraSocial', models.CharField(max_length=45, null=True)),
                ('objetivo', models.CharField(choices=[('perder_peso', 'Perder peso'), ('ganar_masa', 'Ganar masa muscular'), ('mantener', 'Mantener peso'), ('no_definido', 'No definido')], default='no_definido', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('idHistoriaClinica', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.TextField()),
                ('suplemento', models.TextField()),
                ('alergia', models.TextField()),
                ('edad', models.PositiveIntegerField()),
                ('intolerancia', models.TextField()),
                ('anteFamiliar', models.TextField()),
                ('antePatologico', models.TextField()),
                ('patologiaActual', models.TextField()),
                ('hsActiFisica', models.IntegerField()),
                ('tipoActiFisica', models.TextField()),
                ('actiLaboral', models.TextField()),
                ('comentario', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'historiaclinica',
                'unique_together': {('paciente', 'idHistoriaClinica')},
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('idAnamnesis', models.AutoField(primary_key=True, serialize=False)),
                ('habitos', models.CharField(max_length=100)),
                ('preferencia', models.CharField(max_length=100)),
                ('frecConsumo', models.CharField(max_length=100)),
                ('registroComida', models.TextField()),
                ('alimActual', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Anamnesis',
                'unique_together': {('paciente', 'idAnamnesis')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisLab',
            fields=[
                ('idAnalisis', models.AutoField(primary_key=True, serialize=False)),
                ('hepatograma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creatininaSerica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uricemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterolTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uremia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hdl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ldl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trigiceridos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucemia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaB12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('albumina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perritina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('globulosRojos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leucositos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hematocrito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminaD', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_lab', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'AnalisisLab',
                'unique_together': {('paciente', 'idAnalisis')},
            },
        ),
        migrations.CreateModel(
            name='ValorAntropometrico',
            fields=[
                ('idValorAntropometrico', models.AutoField(primary_key=True, serialize=False)),
                ('masaMuscular', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masaGrasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('circunferencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valores_antropometricos', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'ValorAntropometrico',
                'unique_together': {('paciente', 'idValorAntropometrico')},
            },
        ),
    ]
