# Generated by Django 5.1 on 2025-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'Femenino'), ('no_definido', 'No definido')], default='no_definido', max_length=50),
        ),
    ]
