# Generated by Django 5.1 on 2025-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
    ]
