# Generated by Django 5.1 on 2024-12-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comida', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('idPlanN', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('recomendacion', models.TextField()),
                ('comidas', models.ManyToManyField(related_name='planes_nutricionales', to='comida.comida')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricionista', to='persona.nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'planNutricional',
            },
        ),
    ]
