# Generated by Django 5.1 on 2025-01-24 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planNutricional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannutricional',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='hora',
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración en Días'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
