# Generated by Django 5.1 on 2025-03-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='comida.plato'),
        ),
    ]
