# Generated by Django 5.1 on 2025-02-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_remove_plato_comida_alter_plato_descripcion_and_more'),
        ('pacientes', '0002_initial'),
        ('persona', '0002_persona_fechanacimiento'),
        ('planNutricional', '0002_remove_plannutricional_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannutricional',
            name='comidas',
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='platos',
            field=models.ManyToManyField(related_name='planes_nutricionales', to='comida.plato'),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='nutricionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to='persona.nutricionista'),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='pacientes.paciente'),
        ),
    ]
