# Generated by Django 5.1 on 2025-03-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planNutricional', '0002_alter_plandeldia_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeldia',
            name='plato',
        ),
        migrations.AddField(
            model_name='plandeldia',
            name='platos',
            field=models.JSONField(default=list),
        ),
    ]
