# Generated by Django 5.1 on 2025-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planNutricional', '0003_remove_plannutricional_comidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannutricional',
            name='plannutricional',
            field=models.JSONField(default=dict),
        ),
    ]
