# Generated by Django 5.1 on 2025-02-20 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0004_plannutricional_plannutricional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannutricional',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='plannutricional',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='platos',
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha inicio'),
        ),
        migrations.AlterModelTable(
            name='plannutricional',
            table=None,
        ),
        migrations.CreateModel(
            name='PlanDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(verbose_name='Día del Plan')),
                ('tipo_comida', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o Detalles')),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='planNutricional.plannutricional')),
                ('plato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comida.platocomida', verbose_name='Nombre del Plato')),
            ],
            options={
                'ordering': ['dia', 'tipo_comida'],
                'unique_together': {('plan_nutricional', 'dia', 'tipo_comida')},
            },
        ),
    ]
