# Generated by Django 5.1 on 2025-02-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_fechanacimiento'),
        ('planNutricional', '0005_remove_plannutricional_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannutricional',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to='persona.nutricionista'),
        ),
    ]
