# Generated by Django 5.1 on 2025-02-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0006_alter_plannutricional_nutricionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.platocomida', verbose_name='Nombre del Plato'),
        ),
    ]
