# Generated by Django 5.1 on 2025-02-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0007_alter_plandeldia_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plan_nutricional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='planNutricional.plannutricional'),
        ),
        migrations.RemoveField(
            model_name='plandeldia',
            name='plato',
        ),
        migrations.AddField(
            model_name='plandeldia',
            name='plato',
            field=models.ManyToManyField(related_name='planes_dia', to='comida.platocomida', verbose_name='Platos'),
        ),
    ]
