# Generated by Django 5.1 on 2025-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planNutricional', '0008_alter_plandeldia_plan_nutricional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeldia',
            name='plato',
        ),
        migrations.AddField(
            model_name='plandeldia',
            name='plato',
            field=models.TextField(default='[]'),
        ),
    ]
