# Generated by Django 5.1 on 2025-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planNutricional', '0010_alter_plandeldia_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.TextField(),
        ),
    ]
