# Generated by Django 5.1 on 2025-03-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0012_alter_plandeldia_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='comida.platocomida'),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='recomendacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
