# Generated by Django 5.1 on 2025-03-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0013_alter_plandeldia_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_dia', to='comida.platocomida'),
        ),
    ]
