# Generated by Django 5.1 on 2025-03-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0014_alter_plandeldia_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeldia',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.comida'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='descripcion',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='plan_nutricional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planNutricional.plannutricional'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.plato'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='tipo_comida',
            field=models.CharField(max_length=50),
        ),
    ]
