# Generated by Django 5.1 on 2025-03-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_alter_plato_table_alter_platocomida_table'),
        ('planNutricional', '0015_plandeldia_comida_alter_plandeldia_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeldia',
            name='comida',
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción o Detalles'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='dia',
            field=models.PositiveIntegerField(verbose_name='Día del Plan'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='plan_nutricional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='planNutricional.plannutricional'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='comida.platocomida'),
        ),
        migrations.AlterField(
            model_name='plandeldia',
            name='tipo_comida',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='recomendacion',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
