# Generated by Django 5.1 on 2025-01-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idcomida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comidas/')),
                ('calorias', models.IntegerField()),
                ('colesterol', models.FloatField()),
                ('proteina', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasaPolinsaturadas', models.FloatField()),
                ('grasaMoninsaturadas', models.FloatField()),
                ('grasaTrans', models.FloatField()),
                ('grasaTotales', models.FloatField()),
                ('grasaSaturadas', models.FloatField()),
                ('fibraAlimentaria', models.FloatField()),
                ('sodio', models.FloatField()),
                ('reqEnergetico', models.FloatField()),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
    ]
