# Generated by Django 5.1 on 2025-05-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idcomida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/images/comidas/')),
                ('calorias', models.IntegerField()),
                ('colesterol', models.FloatField()),
                ('proteina', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasaPolinsaturadas', models.FloatField()),
                ('grasaMoninsaturadas', models.FloatField()),
                ('grasaTrans', models.FloatField()),
                ('grasaTotales', models.FloatField()),
                ('grasaSaturadas', models.FloatField()),
                ('fibraAlimentaria', models.FloatField()),
                ('sodio', models.FloatField()),
                ('reqEnergetico', models.FloatField()),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('idplato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('merienda', 'Merienda')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'Plato',
            },
        ),
        migrations.CreateModel(
            name='PlatoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=100)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platocomida_set', to='comida.plato')),
            ],
            options={
                'db_table': 'PlatoComida',
            },
        ),
    ]
