# Generated by Django 5.1 on 2025-01-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='categoria',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/comidas/'),
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('idplato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('merienda', 'Merienda')], max_length=50, verbose_name='Tipo de Plato')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles específicos del plato (e.g., ingredientes)', null=True, verbose_name='Descripción del Plato')),
                ('comida', models.ManyToManyField(to='comida.comida', verbose_name='Comida Base')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
        ),
        migrations.CreateModel(
            name='PlatoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=100)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platocomida_set', to='comida.plato')),
            ],
        ),
    ]
