# Generated by Django 5.1 on 2025-01-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_comida_categoria_alter_comida_imagen_plato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='peso',
            field=models.FloatField(default=100),
        ),
        migrations.DeleteModel(
            name='PlatoComida',
        ),
    ]
