# Generated by Django 5.1 on 2025-01-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0003_plato_peso_delete_platocomida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='peso',
        ),
        migrations.CreateModel(
            name='PlatoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=100)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platocomida_set', to='comida.plato')),
            ],
        ),
    ]
