# Generated by Django 5.1 on 2025-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0004_remove_plato_peso_platocomida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='comida',
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('merienda', 'Merienda')], max_length=50),
        ),
    ]
