# Generated by Django 5.1 on 2025-02-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_remove_plato_comida_alter_plato_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plato',
            table='Plato',
        ),
        migrations.AlterModelTable(
            name='platocomida',
            table='PlatoComida',
        ),
    ]
